version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      -  ALLOW_ANONYMOUS_LOGIN=yes
      -  ALLOW_PLAINTEXT_LISTENER=yes
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181





