version: '2'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      -  ALLOW_ANONYMOUS_LOGIN=yes
      -  ALLOW_PLAINTEXT_LISTENER=yes
  kafka:
    image:  'bitnami/kafka:latest'
    ports:
     - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
      # - ALLOW_ANONYMOUS_LOGIN=yes
      #- ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

